userlist = """ */
		G.userList = [
            { uid: 16122,   uname: "Frank Alsheimer",  site: "CAE"  },
            { uid: 29364,   uname: "Warren Blier",     site: "MTR"  },
            { uid: 1691120, uname: "Matthew Kramar",   site: "PBZ"  },
            { uid: 344316,  uname: "Monica Bozeman",   site: "NHC"  },
            { uid: 29573,   uname: "Bruce Entwistle",  site: "AWC"  },
            { uid: 68967,   uname: "Kevin Farina",     site: "MPX"  },
            { uid: 622453,  uname: "John Boris",       site: "MPX"  },
            { uid: 52461,   uname: "Gregory Grosshans",site: "SPC"  },
            { uid: 29684,   uname: "Israel Jirak",     site: "SPC"  },
            { uid: 1691120, uname: "Matthew Kramar",   site: "PBZ"  },
            { uid: 30181,   uname: "Greg Mann",        site: "DTX"  },
            { uid: 93428,   uname: "Kathryn Miretzky", site: "NES"  },
            { uid: 2116452, uname: "Shari Mutchler",   site: "AWC"  },
            { uid: 48571,   uname: "David Radell",     site: "ERHQ" },
            { uid: 54882,   uname: "Eric Guillot",     site: "OBS1", canPlan: true },
            { uid: 99563,   uname: "Brian Rapp",       site: "OBS2", canPlan: true },
            { uid: 39359,   uname: "Joe Zajic",        site: "OBS3", canPlan: true },
            { uid: 322287,  uname: "Lee Byerle",       site: "OBS4", canPlan: true },
            { uid: 2290224, uname: "Jose Harris",      site: "OBS5", canPlan: true },
            { uid: 632648,  uname: "Ted Ryan",         site: "SWD"  },
            { uid: 47926,   uname: "Matthew Seybold",  site: "NES"  },
            { uid: 28993,   uname: "Michael Stavish",  site: "MFR"  },
            { uid: 166322,  uname: "Greg Story",       site: "SWR"  },
            { uid: 2301114, uname: "SDM",              site: "SDM",  canPlan: true },
            { uid: 162099,  uname: "Amanda Terborg",   site: "AWC"  } ];
		/* """
